name: Manual workflow


on:
# push:
 #   branches:
 #   - main
  workflow_dispatch:                                                                                                                 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
           
          

      - name: build the code
        run: npm run build
             
            
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
            name: dist-files
            path: dist
      - name: package
        run: |
           
            mkdir myapp
            cp -r dist/* myapp
            ls myapp
            zip -r myapp.war .
